export default class Types
{
    /** GET BALANCE **/
    static GET_BALANCE_FAILED = 'GET_BALANCE_FAILED';
    static GET_BALANCE_SUCCESS = 'GET_BALANCE_SUCCESS';

    static GET_PREDICTION_FAILED = 'GET_PREDICTION_FAILED';
    static GET_PREDICTION_SUCCESS = 'GET_PREDICTION_SUCCESS';

    static PUT_DATA_BALANCE = 'PUT_DATA_BALANCE';


    /** CLEAR DATA **/
    static CLEAR_DATA_BALANCE = 'CLEAR_DATA_BALANCE';
}
