export const Currencies = [
    { name: "Euro", value: "EUR" },
    { name: "Australian Dollar", value: "AUD" },
    { name: "Bulgarian Lev", value: "BGN" },
    { name: "Brazilian Real", value: "BRL" },
    { name: "Canadian Dollar", value: "CAD" },
    { name: "Swiss Franc", value: "CHF" },
    { name: "Chinese Yuan", value: "CNY" },
    { name: "Czech Koruna", value: "CZK" },
    { name: "Danish Krone", value: "DKK" },
    { name: "British Pound", value: "GBP" },
    { name: "Hong Kong Dollar", value: "HKD" },
    { name: "Hungarian Forint", value: "HUF" },
    { name: "Indonesian Rupiah", value: "IDR" },
    { name: "Israeli New Shekel", value: "ILS" },
    { name: "Indian Rupee", value: "INR" },
    { name: "Icelandic Króna", value: "ISK" },
    { name: "Japanese Yen", value: "JPY" },
    { name: "South Korean Won", value: "KRW" },
    { name: "Mexican Peso", value: "MXN" },
    { name: "Malaysian Ringgit", value: "MYR" },
    { name: "Norwegian Krone", value: "NOK" },
    { name: "New Zealand Dollar", value: "NZD" },
    { name: "Philippine Peso", value: "PHP" },
    { name: "Polish Złoty", value: "PLN" },
    { name: "Romanian Leu", value: "RON" },
    { name: "Swedish Krona", value: "SEK" },
    { name: "Singapore Dollar", value: "SGD" },
    { name: "Thai Baht", value: "THB" },
    { name: "Turkish Lira", value: "TRY" },
    { name: "United States Dollar", value: "USD" },
    { name: "South African Rand", value: "ZAR" }
]

