export default class Types
{
    /** GET EXPENSES **/
    static GET_EXPENSES_FAILED = 'GET_EXPENSES_FAILED';
    static GET_EXPENSES_SUCCESS = 'GET_EXPENSES_SUCCESS';

    static GET_EXPENSE_DETAILS_FAILED = 'GET_EXPENSE_DETAILS_FAILED';
    static GET_EXPENSE_DETAILS_SUCCESS = 'GET_EXPENSE_DETAILS_SUCCESS';

    /** POST EXPENSES **/
    static POST_EXPENSE_FAILED = 'POST_EXPENSE_FAILED';
    static POST_EXPENSE_SUCCESS = 'POST_EXPENSE_SUCCESS';

    /** UPDATE EXPENSES **/
    static PUT_DATA_EXPENSE_FAIL = 'PUT_DATA_EXPENSE_FAIL';
    static PUT_DATA_EXPENSE_SUCCESS = 'PUT_DATA_EXPENSE_SUCCESS';
    static PUT_DATA_EXPENSE = 'PUT_DATA_EXPENSE';

    /** DELETE EXPENSE **/
    static DELETE_EXPENSE_FAIL = 'DELETE_EXPENSE_FAIL';
    static DELETE_EXPENSE_SUCCESS = 'DELETE_EXPENSE_SUCCESS';

    /** CLEAR DATA **/
    static CLEAR_DATA_EXPENSE = 'CLEAR_DATA_EXPENSE';
}
