export default class Tags
{

    static GET_GLOBAL_CONFIG = 'GET_GLOBAL_CONFIG';

    static GET_CURRENCY_EXCHANGE = 'GET_CURRENCY_EXCHANGE';

    // AUTH
    static POST_LOGIN = 'POST_LOGIN';
    static POST_USER = 'POST_USER';
    static GET_USER = 'GET_USER';
    static GET_LOGOUT = 'GET_LOGOUT';
    static PUT_USER = 'PUT_USER';
    static DELETE_USER = 'DELETE_USER';

    // ACCOUNT
    static GET_ACCOUNT_BY_ID = 'GET_ACCOUNT_BY_ID';
    static GET_ACCOUNTS = 'GET_ACCOUNTS';
    static POST_ACCOUNT = 'POST_ACCOUNT';
    static PUT_ACCOUNT = 'PUT_ACCOUNT';
    static DELETE_ACCOUNT = 'DELETE_ACCOUNT';
    static TRANSFER = 'TRANSFER';

    // EXPENSE
    static GET_EXPENSE_BY_ID = 'GET_EXPENSE_BY_ID';
    static GET_EXPENSES = 'GET_EXPENSES';
    static POST_EXPENSE = 'POST_EXPENSE';
    static PUT_EXPENSE = 'PUT_EXPENSE';
    static DELETE_EXPENSE = 'DELETE_EXPENSE';

    // FIXED EXPENSE
    static GET_FIXED_EXPENSE_BY_ID = 'GET_FIXED_EXPENSE_BY_ID';
    static GET_FIXED_EXPENSES = 'GET_FIXED_EXPENSES';
    static POST_FIXED_EXPENSE = 'POST_FIXED_EXPENSE';
    static PUT_FIXED_EXPENSE = 'PUT_FIXED_EXPENSE';
    static DELETE_FIXED_EXPENSE = 'DELETE_FIXED_EXPENSE';

    // INCOME
    static GET_INCOME_BY_ID = 'GET_INCOME_BY_ID';
    static GET_INCOMES = 'GET_INCOMES';
    static POST_INCOME = 'POST_INCOME';
    static PUT_INCOME = 'PUT_INCOME';
    static DELETE_INCOME = 'DELETE_INCOME';

    // CATEGORY
    static GET_CATEGORY_BY_ID = 'GET_CATEGORY_BY_ID';
    static GET_CATEGORIES = 'GET_CATEGORIES';
    static POST_CATEGORY = 'POST_CATEGORY';
    static PUT_CATEGORY = 'PUT_CATEGORY';
    static DELETE_CATEGORY = 'DELETE_CATEGORY';

    // RECIPIENT
    static POST_RECIPIENT = 'POST_RECIPIENT';
    static GET_RECIPIENTS = 'GET_RECIPIENTS';
    // BALANCE
    static GET_BALANCE = 'GET_BALANCE';
    static GET_PREDICTION = 'GET_PREDICTION';
    // GRAPH
    static GET_GRAPH = 'GET_GRAPH';

}
