export default class Types
{
    /** GET EXPENSES **/
    static GET_FIXED_EXPENSES_FAILED = 'GET_FIXED_EXPENSES_FAILED';
    static GET_FIXED_EXPENSES_SUCCESS = 'GET_FIXED_EXPENSES_SUCCESS';

    /** POST EXPENSES **/
    static POST_FIXED_EXPENSE_FAILED = 'POST_FIXED_EXPENSE_FAILED';
    static POST_FIXED_EXPENSE_SUCCESS = 'POST_FIXED_EXPENSE_SUCCESS';

    /** UPDATE EXPENSES **/
    static PUT_DATA_EXPENSE_FAIL = 'PUT_DATA_EXPENSE_FAIL';
    static PUT_DATA_EXPENSE_SUCCESS = 'PUT_DATA_EXPENSE_SUCCESS';
    static PUT_DATA_FIXED_EXPENSE = 'PUT_DATA_FIXED_EXPENSE';

    /** DELETE EXPENSE **/
    static DELETE_EXPENSE_FAIL = 'DELETE_EXPENSE_FAIL';
    static DELETE_EXPENSE_SUCCESS = 'DELETE_EXPENSE_SUCCESS';

    /** CLEAR DATA **/
    static CLEAR_DATA_FIXED_EXPENSE = 'CLEAR_DATA_FIXED_EXPENSE';
}
