export default class Types
{
    /** GET GRAPHS **/
    static GET_INCOME_GRAPHS_FAILED = 'GET_INCOME_GRAPHS_FAILED';
    static GET_INCOME_GRAPHS_SUCCESS = 'GET_INCOME_GRAPHS_SUCCESS';

    static GET_EXPENSE_GRAPHS_FAILED = 'GET_EXPENSE_GRAPHS_FAILED';
    static GET_EXPENSE_GRAPHS_SUCCESS = 'GET_EXPENSE_GRAPHS_SUCCESS';

    static GET_GRAPH_DETAILS_FAILED = 'GET_GRAPH_DETAILS_FAILED';
    static GET_GRAPH_DETAILS_SUCCESS = 'GET_GRAPH_DETAILS_SUCCESS';

    static PUT_DATA_GRAPH = 'PUT_DATA_GRAPH';

    /** CLEAR DATA **/
    static CLEAR_DATA_GRAPH = 'CLEAR_DATA_GRAPH';
}
