export default class Types
{
    /** GET ACCOUNTS **/
    static GET_ACCOUNTS_FAILED = 'GET_ACCOUNTS_FAILED';
    static GET_ACCOUNTS_SUCCESS = 'GET_ACCOUNTS_SUCCESS';

    static GET_ACCOUNT_DETAILS_FAILED = 'GET_ACCOUNT_DETAILS_FAILED';
    static GET_ACCOUNT_DETAILS_SUCCESS = 'GET_ACCOUNT_DETAILS_SUCCESS';

    /** POST ACCOUNTS **/
    static POST_ACCOUNT_FAILED = 'POST_ACCOUNT_FAILED';
    static POST_ACCOUNT_SUCCESS = 'POST_ACCOUNT_SUCCESS';

    /** UPDATE ACCOUNTS **/
    static PUT_DATA_ACCOUNT_FAIL = 'PUT_DATA_ACCOUNT_FAIL';
    static PUT_DATA_ACCOUNT_SUCCESS = 'PUT_DATA_ACCOUNT_SUCCESS';
    static PUT_DATA_ACCOUNT = 'PUT_DATA_ACCOUNT';

    /** DELETE ACCOUNT **/
    static DELETE_ACCOUNT_FAIL = 'DELETE_ACCOUNT_FAIL';
    static DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS';

    /** CLEAR DATA **/
    static CLEAR_DATA_ACCOUNT = 'CLEAR_DATA_ACCOUNT';
}
