export default class Types
{
    /** GET CATEGORIES **/
    static GET_CATEGORIES_FAILED = 'GET_CATEGORIES_FAILED';
    static GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';

    static GET_INIT_CATEGORIES_FAILED = 'GET_INIT_CATEGORIES_FAILED';
    static GET_INIT_CATEGORIES_SUCCESS = 'GET_INIT_CATEGORIES_SUCCESS';

    static GET_CATEGORY_DETAILS_FAILED = 'GET_CATEGORY_DETAILS_FAILED';
    static GET_CATEGORY_DETAILS_SUCCESS = 'GET_CATEGORY_DETAILS_SUCCESS';

    /** POST CATEGORIES **/
    static POST_CATEGORY_FAILED = 'POST_CATEGORY_FAILED';
    static POST_CATEGORY_SUCCESS = 'POST_CATEGORY_SUCCESS';

    /** UPDATE CATEGORIES **/
    static PUT_DATA_CATEGORY_FAIL = 'PUT_DATA_CATEGORY_FAIL';
    static PUT_DATA_CATEGORY_SUCCESS = 'PUT_DATA_CATEGORY_SUCCESS';
    static PUT_DATA_CATEGORY = 'PUT_DATA_CATEGORY';

    /** DELETE CATEGORY **/
    static DELETE_CATEGORY_FAIL = 'DELETE_CATEGORY_FAIL';
    static DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';

    /** CLEAR DATA **/
    static CLEAR_DATA_CATEGORY = 'CLEAR_DATA_CATEGORY';
}
