export default class Types
{
    /** GET RECIPIENTS **/
    static GET_RECIPIENTS_FAILED = 'GET_RECIPIENTS_FAILED';
    static GET_RECIPIENTS_SUCCESS = 'GET_RECIPIENTS_SUCCESS';

    static GET_RECIPIENT_DETAILS_FAILED = 'GET_RECIPIENT_DETAILS_FAILED';
    static GET_RECIPIENT_DETAILS_SUCCESS = 'GET_RECIPIENT_DETAILS_SUCCESS';

    /** POST RECIPIENTS **/
    static POST_RECIPIENT_FAILED = 'POST_RECIPIENT_FAILED';
    static POST_RECIPIENT_SUCCESS = 'POST_RECIPIENT_SUCCESS';

    /** UPDATE RECIPIENTS **/
    static PUT_DATA_RECIPIENT_FAIL = 'PUT_DATA_RECIPIENT_FAIL';
    static PUT_DATA_RECIPIENT_SUCCESS = 'PUT_DATA_RECIPIENT_SUCCESS';
    static PUT_DATA_RECIPIENT = 'PUT_DATA_RECIPIENT';

    /** DELETE RECIPIENT **/
    static DELETE_RECIPIENT_FAIL = 'DELETE_RECIPIENT_FAIL';
    static DELETE_RECIPIENT_SUCCESS = 'DELETE_RECIPIENT_SUCCESS';

    /** CLEAR DATA **/
    static CLEAR_DATA_RECIPIENT = 'CLEAR_DATA_RECIPIENT';
}
