export default class Types
{
    /** GET INCOMES **/
    static GET_INCOMES_FAILED = 'GET_INCOMES_FAILED';
    static GET_INCOMES_SUCCESS = 'GET_INCOMES_SUCCESS';

    static GET_INCOME_DETAILS_FAILED = 'GET_INCOME_DETAILS_FAILED';
    static GET_INCOME_DETAILS_SUCCESS = 'GET_INCOME_DETAILS_SUCCESS';

    /** POST INCOMES **/
    static POST_INCOME_FAILED = 'POST_INCOME_FAILED';
    static POST_INCOME_SUCCESS = 'POST_INCOME_SUCCESS';

    /** UPDATE INCOMES **/
    static PUT_DATA_INCOME_FAIL = 'PUT_DATA_INCOME_FAIL';
    static PUT_DATA_INCOME_SUCCESS = 'PUT_DATA_INCOME_SUCCESS';
    static PUT_DATA_INCOME = 'PUT_DATA_INCOME';

    /** DELETE INCOME **/
    static DELETE_INCOME_FAIL = 'DELETE_INCOME_FAIL';
    static DELETE_INCOME_SUCCESS = 'DELETE_INCOME_SUCCESS';

    /** CLEAR DATA **/
    static CLEAR_DATA_INCOME = 'CLEAR_DATA_INCOME';
}
